openapi: 3.0.0
info:
  title: Franks's calculator Api Doc 
  description: Calculator Api Documentation
  version: 0.1.9
servers:
  - url: http://localhost:8080
    description: Production server
paths:
  /add:
    post:
      summary: This adds two numbers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  $ref: '#/components/schemas/Operands'

      responses: 
        '200':
          description: Created
  /divide:
    post:
      summary: This divides two numbers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  $ref: '#/components/schemas/Operands'

      responses: 
        '200':
          description: You have divided
          
  /subtract:
    post:
      summary: This subtracts two numbers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  $ref: '#/components/schemas/Operands'

      responses: 
        '200':
          description: You have subtracted
  
  /multiply:
    post:
      summary: This multiplys two numbers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  $ref: '#/components/schemas/Operands'
      responses: 
        '200':
          description: You have divided
components:
  schemas:
    Operands:
      properties:
        Operand1:
          type: integer
        Operand2:
          type: integer
      # Both properties are required
      required:  
        - Operand1
        - Operand2
