openapi: 3.0.0
info:
  title: Frank's Hello Rest Service
  description: This is a class assignment used to demonstrate how to mak an API.
  version: 1.0.0
servers:
  - url: http://Localhost:8080
    description: Main (production) server
paths:
  /hello/Frank_Uzoka:
    get:
      summary: Returns hello name.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                items: 
                  type: string